# Generated by Django 4.2.7 on 2026-02-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_healthdata_total_calories_healthdata_total_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='diastolic_bp',
            field=models.IntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='fasting_sugar',
            field=models.FloatField(blank=True, help_text='Fasting blood glucose (mg/dL)', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='post_meal_sugar',
            field=models.FloatField(blank=True, help_text='Post-meal blood glucose (mg/dL)', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='systolic_bp',
            field=models.IntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True),
        ),
    ]
