# Generated by Django 4.2.7 on 2026-03-08 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_cardiometabolic_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='diastolic_bp',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='fasting_sugar',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='post_meal_sugar',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='systolic_bp',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='daily_steps',
            field=models.IntegerField(blank=True, help_text='Number of daily steps', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='stress_level',
            field=models.IntegerField(blank=True, help_text='Stress level (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
