# Generated by Django 4.2.7 on 2026-03-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_remove_healthdata_diastolic_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
