# Generated by Django 4.2.7 on 2026-03-08 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_alter_healthdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
